# Generated by Django 4.2.9 on 2024-04-20 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_room_description_alter_room_amount_and_more'),
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarding',
            name='room_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.room'),
        ),
    ]
